-- Inclui estágios já existentes na ocupação semestral, sem duplicar reservas do formulário.
create or replace function public.get_advisor_availability(p_start_date date default current_date)
returns table(id uuid,name text,areas text,display_order integer,max_selections integer,current_selections bigint,remaining_selections bigint,available boolean)
language sql stable security definer set search_path=public as $$
with occupancy as(select a.id,(select count(*) from public.advisor_assignments s where s.advisor_id=a.id and s.semester_year=extract(year from coalesce(p_start_date,current_date))::integer and s.semester_half=case when extract(month from coalesce(p_start_date,current_date))<=6 then 1 else 2 end)+(select count(*) from public.internships i where lower(trim(i.advisor_name))=lower(trim(a.name)) and i.start_date is not null and extract(year from i.start_date)::integer=extract(year from coalesce(p_start_date,current_date))::integer and (case when extract(month from i.start_date)<=6 then 1 else 2 end)=case when extract(month from coalesce(p_start_date,current_date))<=6 then 1 else 2 end and not exists(select 1 from public.advisor_assignments s where s.protocol is not null and s.protocol=i.public_protocol)) as occupied from public.internship_advisors a where a.is_active=true)
select a.id,a.name,a.areas,a.display_order,a.max_selections,o.occupied,greatest(a.max_selections-o.occupied,0),o.occupied<a.max_selections from public.internship_advisors a join occupancy o on o.id=a.id order by a.display_order,a.name;$$;
revoke all on function public.get_advisor_availability(date) from public;grant execute on function public.get_advisor_availability(date) to anon,authenticated;
create or replace function public.reserve_advisor_slot(p_advisor_name text,p_protocol text,p_start_date date)
returns void language plpgsql security definer set search_path=public as $$
declare selected_advisor public.internship_advisors%rowtype;selected_year integer:=extract(year from p_start_date)::integer;selected_half smallint:=case when extract(month from p_start_date)<=6 then 1 else 2 end;occupied integer;
begin if auth.role()<>'service_role' and not public.is_coeri_admin() then raise exception 'Acesso não autorizado';end if;if exists(select 1 from public.advisor_assignments where protocol=p_protocol) then return;end if;select * into selected_advisor from public.internship_advisors where is_active=true and lower(trim(name))=lower(trim(p_advisor_name)) for update;if not found then raise exception 'ADVISOR_NOT_AVAILABLE';end if;
select (select count(*) from public.advisor_assignments s where s.advisor_id=selected_advisor.id and s.semester_year=selected_year and s.semester_half=selected_half)+(select count(*) from public.internships i where lower(trim(i.advisor_name))=lower(trim(selected_advisor.name)) and i.start_date is not null and extract(year from i.start_date)::integer=selected_year and (case when extract(month from i.start_date)<=6 then 1 else 2 end)=selected_half and not exists(select 1 from public.advisor_assignments s where s.protocol is not null and s.protocol=i.public_protocol)) into occupied;
if occupied>=selected_advisor.max_selections then raise exception 'ADVISOR_CAPACITY_REACHED';end if;insert into public.advisor_assignments(advisor_id,protocol,semester_year,semester_half) values(selected_advisor.id,p_protocol,selected_year,selected_half);end;$$;
revoke all on function public.reserve_advisor_slot(text,text,date) from public;grant execute on function public.reserve_advisor_slot(text,text,date) to authenticated,service_role;